name: Build EXE

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
        
    - name: Install dependencies
      run: |
        pip install pyinstaller numpy sounddevice
        
    - name: Build EXE
      run: |
        # 這是你的打包指令
        pyinstaller --onefile --windowed app.py
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        files: dist/app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
